grpc:
  server:
    port: 59091
    reflection-service-enabled: true

# Автоматическое связывание с KafkaTemplate
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: "recomm.collector"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.practicum.recomm.kafka.serializer.GeneralAvroSerializer
    consumer:
      client-id: "recomm.collector"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.practicum.recomm.kafka.deserializer.UserActionDeserializer

# Маппинг логических имен топиков на реальные имена в Kafka
collector:
  kafka:
    producer:
      topics:
        user-events: "stats.user-actions.v1"