spring:
  application:
    name: config-server  # Имя сервиса в сервис-дисковере (Eureka)
  profiles:
    active: native  # Активный профиль — использование локальных конфигов из classpath
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/stats/{application}  # Конфигурации для сервиса stats
            - classpath:config/core/{application}   # Конфигурации для сервиса core
            - classpath:config/infra/{application}  # Конфигурации для инфраструктурных сервисов
server:
  port: 0  # Автоматически выбирает свободный порт, удобно для тестирования и CI/CD

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/