-- Таблица для хранения действий пользователей с мероприятиями
CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,                -- Вес взаимодействия
    interact_at TIMESTAMP WITH TIME ZONE NOT NULL,  -- Время взаимодействия с учетом временной зоны
    CONSTRAINT unique_user_event UNIQUE (user_id, event_id)
);

-- Таблица для хранения сходства между мероприятиями
CREATE TABLE IF NOT EXISTS event_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id BIGINT NOT NULL,                                        -- Идентификатор исходного мероприятия
    target_event_id BIGINT NOT NULL,                                        -- Идентификатор целевого мероприятия
    similarity_score DOUBLE PRECISION NOT NULL,                             -- Степень сходства (0.0 - 1.0)
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,                        -- Время расчёта сходства
    CONSTRAINT unique_event_pair UNIQUE (source_event_id, target_event_id),
    CONSTRAINT valid_event_order CHECK (source_event_id < target_event_id)  -- Избегаем дублирования пар
);