-- Таблица для хранения статистики HTTP-запросов (hits)
CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Уникальный идентификатор записи
    app       VARCHAR(255) NOT NULL,                              -- Имя сервиса (приложения), к которому относится запрос
    uri       TEXT         NOT NULL,                              -- URI, по которому был выполнен запрос
    ip        VARCHAR(45)  NOT NULL,                              -- IP-адрес пользователя (IPv4 или IPv6)
    timestamp TIMESTAMP    NOT NULL                               -- Временная метка запроса
);