server:
  port: 0  # Используется случайный порт для тестирования в контейнерах
  servlet:
    encoding:
      force: true  # Принудительное использование UTF-8 для всех запросов/ответов
      charset: UTF-8

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # Глобальный формат даты для java.util.Date
    serialization:
      write-dates-as-timestamps: false  # Отправляем даты в читаемом виде, а не как таймстемпы
    default-property-inclusion: non_null  # Игнорируем null-значения при сериализации JSON

  jpa:
    hibernate.ddl-auto: none  # Отключение автоматического управления схемой БД
    properties:
      hibernate:
        format_sql: false  # Отключаем форматирование SQL-запросов
        connection:
          read_only: false  # База не находится в режиме только для чтения

  sql:
    init:
      mode: always  # Всегда загружать инициализационные скрипты при старте

  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost:6432/requests_db  # URL к локальной БД
    username: ewm-request  # Имя пользователя БД
    password: ewm-request  # Пароль пользователя БД

logging:
  level:
    org:
      springframework:
        web: INFO  # Логирование HTTP-запросов/ответов
        http:
          converter: INFO  # Подробное логирование конвертеров HTTP
        orm:
          jpa: INFO  # Логирование операций JPA
          jpa.JpaTransactionManager: INFO  # Логирование транзакций JPA
        transaction:
          TransactionInterceptor: INFO  # Логирование Spring Transaction Interceptor

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext