CREATE TABLE participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT      NOT NULL,
    requester_id BIGINT      NOT NULL,
    created      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       VARCHAR(20) NOT NULL,
    UNIQUE (event_id, requester_id)
);