server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**, /admin/**, /users/**, /events/**, /compilations/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO
    reactor.netty: INFO

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true