server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: request-service
              uri: lb://request-service
              predicates:
                - Path=/users/{userId}/requests/**, /users/{userId}/events/{eventId}/requests

            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/admin/**, /compilations/**, /categories/**, /events/**, /users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    env:
      enabled: true