server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/admin/users/**

            - id: main-service
              uri: lb://main-service
              predicates:
                - Path=/admin/categories/**, /admin/comments/**, /admin/compilations/**, /admin/events/**, /compilations/**, /categories/**, /events/**, /users/**

            - id: stats-server
              uri: lb://stats-server
              predicates:
                - Path=/hit/**, /stats/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health
  info:
    env:
      enabled: true