server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:explorewithme;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: ewm-main
    password: ewm-main

logging:
  level:
    org:
      springframework:
        orm:
          jpa: TRACE
          jpa.JpaTransactionManager: TRACE
        transaction: TRACE
        transaction.interceptor: TRACE
      hibernate:
        SQL: TRACE
        type.descriptor.sql.BasicBinder: TRACE
      zalando:
        logbook: TRACE