@namespace("ru.practicum.recommendations.avro")
protocol EventSimilarityProtocol {

	/**
	 * Запись, представляющая пару похожих мероприятий и их уровень сходства.
	 *
	 * Используется для хранения результатов анализа сходства между мероприятиями.
	 */
	record EventSimilarityAvro {
		/**
		 * Идентификатор первого мероприятия в паре.
		 *
		 * Представляет собой исходное мероприятие.
		 */
		long eventA;

		/**
		 * Идентификатор второго мероприятия в паре.
		 *
		 * Представляет собой мероприятие, похожее на первое.
		 */
		long eventB;

		/**
		 * Числовой показатель сходства между двумя мероприятиями.
		 *
		 * Значение находится в диапазоне [0, 1], где:
		 * - 0 означает полное отсутствие сходства,
		 * - 1 означает полное совпадение.
		 */
		double score;

		/**
		 * Временная метка, указывающая, когда была рассчитана схожесть.
		 *
		 * Хранится в миллисекундах с эпохи Unix.
		 */
		timestamp_ms timestamp;
	}
}