@namespace("ru.practicum.recommendations.avro")
protocol UserActionProtocol {

	/**
	 * Перечисление типов пользовательских действий.
	 *
	 * Описывает возможные виды взаимодействия пользователя с мероприятиями:
	 * - VIEW: просмотр страницы мероприятия
	 * - REGISTER: регистрация на мероприятие
	 * - LIKE: положительная оценка мероприятия
	 */
	enum ActionTypeAvro {
		VIEW,
		REGISTER,
		LIKE
	}

	/**
	 * Запись, представляющая действие пользователя, отправляемое в систему рекомендаций.
	 *
	 * Содержит информацию о пользователе, мероприятии, типе действия и моменте совершения действия.
	 */
	record UserActionAvro {
		long user_id;
		long event_id;
		ActionTypeAvro actionType;

		/**
		 * Временная метка, указывающая момент совершения действия.
		 *
		 * Хранится в миллисекундах с эпохи Unix.
		 */
		timestamp_ms timestamp;
	}
}